### ISSUE TITLE
Automate release workflow, switch to GitHub releases

### ISSUE THREAD

**Issue by PetteriAimonen** [nanopb/nanopb#1041]
Nanopb has been using custom hosted download server as back when it was set up, GitHub didn't have releases functionality yet.

Nowadays it would simplify release management to have them as GitHub releases instead.

**Comment by tpudlik** [comment]
As part of the release workflow, could [the version in MODULE.bazel](https://github.com/nanopb/nanopb/blob/master/MODULE.bazel#L3) be incremented? I noticed this was not done for the 0.4.9.1 release. I patched this line when adding the release to the Bazel Central Registry, but it would be nice for it to be correct in the source.

**Comment by PetteriAimonen** [comment]
Yeah, that should be added to `set_version.sh`: https://github.com/nanopb/nanopb/blob/master/tools/set_version.sh

**Comment by weichslgartner** [comment]
Could the version information also be added to `zephyr/module.yml` (see https://docs.zephyrproject.org/latest/develop/modules.html#vulnerability-monitoring). This would enable to generate SBOMs in zephyr projects using nanopb.

For example adding CPE and PURL for version 0.4.0 would look like:
```yml
security:
  external-references:
    - cpe:2.3:a:nanopb_project:nanopb:0.4.0:*:*:*:*:*:*:*
    - pkg:github/nanopb/nanopb@V0.4.0
```
